# 服务器文件路径
product.manual.path=C:/Users/zhx/Desktop/新版本舆情产品手册V1.0.pdf
#???????
llm.dashCope.key =
llm.dashCope.url = https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
llm.dashCope.model = qwen-plus
#???????
llm.dashCope.flag = false

nlp.service.open=false

nlp.service.url=https://nlp.stonedt.com

nlp.service.username =

npl.service.password =